---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  volumes: [ '/var/lib/docker' ]

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which net-tools procps-ng telnet iputils nmap
  run_list:
    - recipe[chef-yum-docker]

suites:
  - name: default
    driver:
      chef_version: latest
    run_list:
    - recipe[dokken_test::default]

  - name: hello
    driver:
      chef_version: latest
      hostname: hello.computers.biz
      ports: "1234"
    run_list:
    - recipe[dokken_test::hello]

  - name: helloagain
    driver:
      chef_version: latest
      hostname: helloagain.computers.biz
      ports:
        - '8301'
        - '8301:8301/udp'
        - '127.0.0.1:8500:8500'
    run_list:
    - recipe[dokken_test::helloagain]
